using BGPLite.Api;

namespace BGPLite.Tests;

/// <summary>
/// Tests for the GET /api/server router-setup templates (Cisco / BIRD / MikroTik) — #218.
/// The templates are generated by the pure Build*Setup helpers (no DI), so they can be exercised
/// directly. The critical invariant is multihop: every platform must enable it, otherwise a client
/// that is NOT directly connected to the server (NAT/upstream transit) drops the TCP to :179 before
/// OPEN and the session never establishes.
/// </summary>
public class ServerSetupTemplateTests
{
    private const uint Asn = 65444;
    private const string RouterId = "31.207.44.205";
    private const int HoldTime = 180;

    [Fact]
    public void Mikrotik_Setup_Enables_Multihop()
    {
        var lines = ManagementApi.BuildMikrotikSetup(RouterId, Asn, HoldTime);

        // The connection line must carry multihop=yes — without it, RouterOS v7 (multihop=no default)
        // drops inbound TCP to :179 before OPEN for non-directly-connected peers (#218).
        var connectionLine = Assert.Single(lines, l => l.StartsWith("/routing/bgp/connection/add"));
        Assert.Contains("multihop=yes", connectionLine);
        // Sanity: the rest of the connection line is still intact (regression guard).
        Assert.Contains($"remote.address={RouterId}/32", connectionLine);
        Assert.Contains($"remote.as={Asn}", connectionLine);
        Assert.Contains($"hold-time={HoldTime}s", connectionLine);
        Assert.Contains("local.role=ebgp", connectionLine);
    }

    [Fact]
    public void Cisco_Setup_Enables_Multihop()
    {
        var lines = ManagementApi.BuildCiscoSetup(Asn);

        // Cisco equivalent of multihop — already correct, guard against regression.
        Assert.Contains(lines, l => l.Contains("ebgp-multihop 2"));
        Assert.Contains(lines, l => l.Contains($"remote-as {Asn}"));
    }

    [Fact]
    public void Bird_Setup_Enables_Multihop()
    {
        var lines = ManagementApi.BuildBirdSetup(RouterId, Asn, HoldTime);

        // BIRD equivalent of multihop — already correct, guard against regression.
        Assert.Contains(lines, l => l.Trim() == "multihop;");
        Assert.Contains(lines, l => l.Contains($"neighbor {RouterId} as {Asn};"));
    }
}
