// <auto-generated />
using System;
using BGPLite.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BGPLite.Api.Migrations
{
    [DbContext(typeof(BgpDbContext))]
    [Migration("20260901102233_AddPeerMaxPrefix")]
    partial class AddPeerMaxPrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BGPLite.Api.Entities.Peer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Asn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSessionAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("inactive");

                    b.HasKey("Id");

                    b.HasIndex("Ip", "Asn")
                        .IsUnique()
                        .HasDatabaseName("UX_Peers_Ip_Asn");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCommunity", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Community")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId", "Community");

                    b.ToTable("PeerCommunity");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomAsn", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Asn")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId", "Asn");

                    b.ToTable("PeerCustomAsns", (string)null);
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomPrefix", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId", "Prefix", "PrefixLength");

                    b.ToTable("PeerCustomPrefix");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Community")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PeerCustomSources", (string)null);
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerSubscription", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AsnListName")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerId", "AsnListName");

                    b.ToTable("PeerSubscription");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCommunity", b =>
                {
                    b.HasOne("BGPLite.Api.Entities.Peer", "Peer")
                        .WithMany("Communities")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomAsn", b =>
                {
                    b.HasOne("BGPLite.Api.Entities.Peer", "Peer")
                        .WithMany("CustomAsns")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomPrefix", b =>
                {
                    b.HasOne("BGPLite.Api.Entities.Peer", "Peer")
                        .WithMany("CustomPrefixes")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerCustomSource", b =>
                {
                    b.HasOne("BGPLite.Api.Entities.Peer", "Peer")
                        .WithMany("CustomSources")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.PeerSubscription", b =>
                {
                    b.HasOne("BGPLite.Api.Entities.Peer", "Peer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("BGPLite.Api.Entities.Peer", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("CustomAsns");

                    b.Navigation("CustomPrefixes");

                    b.Navigation("CustomSources");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
